const std = @import("std");
const zephyr = @import("zephyr");

pub fn main(init: std.process.Init) !void {
    // const gpa = init.arena.allocator();
    var dba = std.heap.DebugAllocator(.{}).init;
    const gpa = dba.allocator();
    const args = try init.minimal.args.toSlice(gpa);
    if (args.len != 3) std.process.fatal("usage: vk_generator <vk.xml path> <output vk.zig path>", .{});

    const vk_xml_path = args[1];
    const output_path = args[2];

    const xml = try std.Io.Dir.cwd().readFileAlloc(init.io, vk_xml_path, gpa, .limited(max_registry_bytes));

    var out: std.ArrayList(u8) = .empty;
    try generate(gpa, xml, &out);

    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = output_path, .data = out.items });
}

/// Upper bound on the size of a vk.xml we are willing to read.
pub const max_registry_bytes = 64 * 1024 * 1024;

/// Parse a Vulkan registry (the contents of vk.xml) and append the complete
/// generated `vk.zig` source to `out`.
pub fn generate(gpa: std.mem.Allocator, xml: []const u8, out: *std.ArrayList(u8)) !void {
    var registry = try zephyr.registry.parse(gpa, xml);
    defer registry.deinit(gpa);

    try out.appendSlice(gpa, "// AUTO-GENERATED by modules/zephyr/src/vk_generator -- DO NOT EDIT\n\n");
    try out.appendSlice(gpa, "const std = @import(\"std\");\n\n");
    try out.appendSlice(gpa, @embedFile("preamble.vk.zig"));
    try out.appendSlice(gpa, "\n");

    try zephyr.emit.write(gpa, &registry, out);
}

/// Path of the registry shipped with an installed Vulkan SDK.
fn registryPathAlloc(gpa: std.mem.Allocator, sdk_path: []const u8) ![]u8 {
    return std.fs.path.join(gpa, &.{ sdk_path, "share", "vulkan", "registry", "vk.xml" });
}

test "generate bindings from the installed Vulkan SDK registry" {
    // The generator warns about every registry entry it can't represent
    // (Metal/Xlib/SciBuf interop, mostly); that is expected, not a failure.
    std.testing.log_level = .err;

    // The emitter allocates transient strings and relies on the CLI process
    // exiting to reclaim them, so give it an arena rather than tripping the
    // testing allocator's leak detector on every one of them.
    var arena_state: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena_state.deinit();
    const gpa = arena_state.allocator();

    const sdk_path = std.testing.environ.getAlloc(gpa, "VULKAN_SDK") catch |err| switch (err) {
        error.EnvironmentVariableMissing => return error.SkipZigTest,
        else => |e| return e,
    };
    const vk_xml_path = try registryPathAlloc(gpa, sdk_path);
    const xml = std.Io.Dir.cwd().readFileAlloc(
        std.testing.io,
        vk_xml_path,
        gpa,
        .limited(max_registry_bytes),
    ) catch |err| switch (err) {
        // An SDK without the registry component installed is not a generator bug.
        error.FileNotFound => return error.SkipZigTest,
        else => |e| return e,
    };

    var out: std.ArrayList(u8) = .empty;
    try generate(gpa, xml, &out);

    // A handle, a plain enum, a bitmask, a struct and a baseline command:
    // one of each emitter path, so a silently empty section fails here.
    for ([_][]const u8{
        "pub const Instance = enum(usize)",
        "pub const StructureType = enum(",
        "pub const QueueFlags = packed struct(",
        "pub const InstanceCreateInfo = extern struct",
        "pub fn createInstance(",
    }) |needle| {
        std.testing.expect(std.mem.indexOf(u8, out.items, needle) != null) catch |err| {
            std.debug.print("missing from generated bindings: {s}\n", .{needle});
            return err;
        };
    }
}
